# Generated by Django 3.2.8 on 2021-10-10 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurante.restaurante'),
        ),
    ]
