# Generated by Django 3.2.8 on 2021-10-10 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_id'),
        ('producto', '0002_producto_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido'),
        ),
    ]
