# Generated by Django 3.2.8 on 2021-10-14 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_alter_restaurante_id'),
        ('producto', '0004_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurante.restaurante'),
        ),
    ]
