# Generated by Django 3.2.8 on 2021-10-14 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_alter_restaurante_id'),
        ('pedido', '0004_auto_20211014_1157'),
        ('producto', '0005_alter_producto_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pedido',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurante.restaurante'),
        ),
    ]
