# Generated by Django 3.2.8 on 2021-10-14 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_auto_20211014_1157'),
        ('producto', '0006_auto_20211014_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pedido',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido'),
        ),
    ]
