# Generated by Django 3.2.8 on 2021-10-10 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_id'),
        ('calificacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='id',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='pedido',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pedido.pedido'),
        ),
    ]
