# Generated by Django 3.2.6 on 2021-12-09 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hub',
            old_name='direcccion',
            new_name='direccion',
        ),
    ]
