# Generated by Django 3.2.6 on 2021-10-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('dateTime', models.DateTimeField()),
                ('precio', models.FloatField(blank=True, default=None, null=True)),
                ('estado', models.CharField(choices=[('OR', 'Ordenado'), ('CN', 'Cancelado'), ('EP', 'En preparación'), ('H1', 'En hub de salida'), ('VL', 'Volando'), ('H2', 'En hub de entrega'), ('EN', 'Entregado')], default='EP', max_length=2)),
            ],
        ),
    ]
