# Generated by Django 3.2.6 on 2021-10-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprador', '0002_alter_comprador_id'),
        ('hub', '0001_initial'),
        ('pedido', '0003_alter_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comprador.comprador'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hub',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hub.hub'),
        ),
    ]
